#!/usr/bin/env bash

set -o errexit
test -e .env && source .env || echo "$0: warn: no '.env' file in $(pwd): default values will be used"

readonly APPNAME="${APPNAME:-myapp}"
readonly APPVERSION="${APPVERSION:-latest}"

readonly TMPDIR="/tmp/git-post-commit"
test -d $TMPDIR || mkdir -p $TMPDIR

readonly LOGFILE=$(mktemp -q ${TMPDIR}/${APPNAME}-`date '+%Y%m%d-%H%M%S'`-XXX)
exec 1>$LOGFILE
exec 2>&1

docker build -t ${APPNAME}:${APPVERSION} -f Dockerfile .
docker-compose -f docker-compose.yaml up -d --no-deps --build
docker system prune -f
